// Generated by CoffeeScript 1.3.3
(function() {
  var Faqify;

  Faqify = (function() {

    Faqify.prototype.baseUrl = 'http://tranquil-dusk-4165.herokuapp.com';

    Faqify.prototype.isOpen = false;

    Faqify.prototype.baseHtml = '<div id="faqify">\
		<div id="faqify_header">\
			<span>Check out the FAQ</span>\
			<div class="arrow_up"></div>\
		</div>\
		<div id="faqify_actions">\
			<span>Ask a Question!</span>\
		</div>\
		<ul id="faqify_list"></ul>\
	</div>\
	<div id="faqify_modal"></div>\
	<div id="faqify_modal_background"></div>';

    Faqify.prototype.askQuestionHtml = '<div class="remove_modal">X</div>\
		<div id="ask_question_modal">\
		<h1>Ask a Question</h1>\
		<form>\
			<label>Title</label>\
			<input type="text" name="faqify_title" />\
			<label>So what do you need to know?</label>\
			<textarea name="faqify_description"></textarea>\
			<button id="ask_button">Ask Question</button>\
		</form>\
		</div>';

    Faqify.prototype.viewQuestionHtml = function(question) {
      var html;
      return html = "<div class='remove_modal'>X</div>		<div id='view_question_modal' data-question_id='" + question._id + "'>		<h2>Q: " + question.title + "</h2>		<p>" + question.description + "</p>		<h2 class='answer_header'>Answers</h2>		" + (question.answers.length === 0 ? '<p class="no_answers">No answers yet</p>' : '') + "		<ul class='answers'></ul>		<form>			<textarea placeholder='Post an answer' name='faqify_description'></textarea>			<button id='answer_button'>Post Answer</button>		</form>		</div>";
    };

    function Faqify(apiKey) {
      this.apiKey = apiKey;
      $('body').append(this.baseHtml);
      apiKey = this.apiKey;
      $.ajaxSetup({
        headers: {
          faqify_api_key: apiKey
        }
      });
      this.bindEvents();
      this.getQuestions();
    }

    Faqify.prototype.findQuestion = function(_id) {
      var question, _i, _len, _ref;
      _ref = this.questions;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        question = _ref[_i];
        if (question._id === _id) {
          return question;
        }
      }
    };

    Faqify.prototype.open = function() {
      $('#faqify_header .arrow_up').removeClass('arrow_up').addClass('arrow_down');
      $('#faqify_actions').show();
      $('#faqify_list').show();
      return this.isOpen = true;
    };

    Faqify.prototype.close = function() {
      $('#faqify').css('width', '177px');
      $('#faqify .arrow_down').removeClass('arrow_down').addClass('arrow_up');
      $('#faqify_actions').hide();
      $('#faqify_list').hide();
      return this.isOpen = false;
    };

    Faqify.prototype.askQuestion = function() {
      var centerModal;
      centerModal = ($('html').width() - 600) / 2;
      $('#faqify_modal').css({
        left: centerModal
      }).html('').html(this.askQuestionHtml).show();
      return $('#faqify_modal_background').css({
        height: $('html').height(),
        width: $('html').width()
      }).show();
    };

    Faqify.prototype.viewQuestion = function(event) {
      var answer, answerLi, centerModal, question, _i, _len, _ref;
      centerModal = ($('html').width() - 600) / 2;
      question = this.findQuestion($(event.currentTarget).data('question_id'));
      $('#faqify_modal').css({
        left: centerModal
      }).html('').html(this.viewQuestionHtml(question));
      _ref = question.answers;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        answer = _ref[_i];
        answerLi = "<li><div class='faqify_arrow_right'></div>" + answer.description + "</li>";
        $('#view_question_modal .answers').append(answerLi);
      }
      $('#faqify_modal').show();
      return $('#faqify_modal_background').css({
        height: $('html').height(),
        width: $('html').width()
      }).show();
    };

    Faqify.prototype.closeModal = function() {
      $('#faqify_modal').html('').hide();
      return $('#faqify_modal_background').hide();
    };

    Faqify.prototype.saveQuestion = function(event) {
      var baseUrl, data, errorCb, successCb,
        _this = this;
      event.preventDefault();
      data = {
        title: $('input[name="faqify_title"]').val(),
        description: $('textarea[name="faqify_description"]').val()
      };
      baseUrl = this.baseUrl;
      successCb = function(question) {
        var li, realQuestion;
        realQuestion = question.question;
        _this.questions.push(realQuestion);
        li = "<li data-question_id='" + realQuestion._id + "'>" + realQuestion.title + "</li>";
        $('#faqify_list').prepend(li);
        _this.close();
        return $("#faqify li[data-question_id='" + realQuestion._id + "']").click();
      };
      errorCb = function(a, b, c) {
        return console.log(a, b, c);
      };
      return $.ajax({
        url: "" + baseUrl + "/questions",
        data: data,
        type: 'POST',
        success: successCb,
        error: errorCb
      });
    };

    Faqify.prototype.saveAnswer = function(event) {
      var baseUrl, data, errorCb, question_id, successCb,
        _this = this;
      event.preventDefault();
      question_id = $('#view_question_modal').data('question_id');
      data = {
        description: $('textarea[name="faqify_description"]').val(),
        question_id: question_id
      };
      baseUrl = this.baseUrl;
      successCb = function(answer) {
        var answerLi, question, realAnswer;
        realAnswer = answer.answer;
        question = _this.findQuestion(question_id);
        question.answers.push(realAnswer);
        $('#view_question_modal .no_answers').remove();
        answerLi = "<li><div class='faqify_arrow_right'>" + realAnswer.description + "</li>";
        return $('#view_question_modal .answers').append(answerLi);
      };
      errorCb = function(a, b, c) {
        return console.log(a, b, c);
      };
      return $.ajax({
        url: "" + baseUrl + "/answers",
        data: data,
        type: 'POST',
        success: successCb,
        error: errorCb
      });
    };

    Faqify.prototype.bindEvents = function() {
      var _this = this;
      $('#faqify_header').on('click', function() {
        if (_this.isOpen === false) {
          return _this.open();
        } else {
          return _this.close();
        }
      });
      $('#faqify_actions span').on('click', function() {
        return _this.askQuestion();
      });
      $('#faqify_modal_background').on('click', function() {
        return _this.closeModal();
      });
      $(document).on('click', '#ask_question_modal button', function(event) {
        return _this.saveQuestion(event);
      });
      $(document).on('click', '.remove_modal', function() {
        return _this.closeModal();
      });
      $(document).on('click', '#faqify_list li', function(event) {
        return _this.viewQuestion(event);
      });
      return $(document).on('click', '#view_question_modal button', function(event) {
        return _this.saveAnswer(event);
      });
    };

    Faqify.prototype.populateList = function() {
      var li, question, _i, _len, _ref, _results;
      _ref = this.questions;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        question = _ref[_i];
        li = "<li data-question_id='" + question._id + "'>" + question.title + "</li>";
        _results.push($('#faqify_list').append(li));
      }
      return _results;
    };

    Faqify.prototype.getQuestions = function() {
      var baseUrl, errorCb, successCb,
        _this = this;
      baseUrl = this.baseUrl;
      successCb = function(questions) {
        _this.questions = questions.data;
        return _this.populateList();
      };
      errorCb = function(a, b, c) {
        return console.log(a, b, c);
      };
      return $.ajax({
        url: "" + baseUrl + "/questions",
        success: successCb,
        error: errorCb
      });
    };

    return Faqify;

  })();

  window.Faqify = Faqify;

}).call(this);
